### ISSUE TITLE
可以问一下作者用什么分析支付宝的逻辑吗

### ISSUE THREAD

**Issue by ananas-xxj** [nov30th/AlipayHighHeadsomeRichAndroid#1]
一般般app 用反编译工具反编译过来  很多方法名都是乱的，请问大佬怎么分析的

**Comment by nov30th** [comment]
有动态静态反编译。另外可以通过界面显示部分的调用找到相关函数。作者不是专门搞app也不是搞反编译这一块的，所以讲不好应该从哪里去分析。对于这个hook，作者在金融行业所以是找几个熟悉的关键词便找到了。
