### ISSUE TITLE
能否在我的页面把支付宝会员也改成钻石会员

### ISSUE THREAD

**Issue by NekoMua** [nov30th/AlipayHighHeadsomeRichAndroid#10]
(`･ω･´)ゞ

**Comment by nov30th** [comment]
由于作者已经是钻石会员了所以……暂时不会去研究。
如果要新增功能的话，我可能会增加个自动偷能量啥的，不过还没时间去研究hook网页请求啥的，所以应该目前也不会增加。

**Comment by NekoMua** [comment]
> 由于作者已经是钻石会员了所以……暂时不会去研究。
> 如果要新增功能的话，我可能会增加个自动偷能量啥的，不过还没时间去研究hook网页请求啥的，所以应该目前也不会增加。

富哥V50😋

**Comment by nov30th** [comment]
💰x50 hhh
