### ISSUE TITLE
Please upload some exported skins, thank you.

### ISSUE THREAD

**Issue by LuminousPendulum** [nov30th/AlipayHighHeadsomeRichAndroid#12]
Please upload some exported skins, thank you.

**Comment by LuminousPendulum** [comment]
Official skin, I mean.

**Comment by nov30th** [comment]
This is a personal project with limited functionality. Even official skins are time-limited, and skin creators are under contract, making unauthorized use legally risky.  The primary purpose is to customize background images for individual use. Additionally, you have the option to export images and share them with friends' accounts, if desired.

**Comment by LuminousPendulum** [comment]
Now it seems that I need some friends who have purchased skins, you know what i mean, right? My friend. :D
