### ISSUE TITLE
装逼进行到底

### ISSUE THREAD

**Issue by pidanpro** [nov30th/AlipayHighHeadsomeRichAndroid#16]
有个 《 财富黑卡》皮肤挺火，大佬会考虑更新吗？

**Comment by nov30th** [comment]
我是财富黑卡v3 emmm，倒是可以导出来做到SD资源包里。但是最近入了一个小米flip手机，要等9月份那什么8点的考试……

目前手机上没用root，因为微X新版本也用不了就等账号root权限拿到了之后再更新。

你也可以用别人有这个皮肤的账号，创建一个export文件夹（首页说明有导出步骤），导出后，其他账号都能共用这个皮肤。

**Comment by pidanpro** [comment]
> 我是财富黑卡v3 emmm，倒是可以获取来实现SD资源包里。但是最近入了一个小米翻盖手机，要等9月份那什么8点的考试……
> 
> 目前手机上没用root，因为微X新版本也用不了就等账号root权限获得了之后再更新。
> 
> 你也可以用别人有这个皮肤的账号，创建一个export文件夹（首页说明有导出步骤），导出后，其他账号共用这个皮肤。

还是等大佬更新吧，身边没人有黑卡皮肤

**Comment by nov30th** [comment]
噩耗，前两天看到小米社区说今年关闭BL解锁名额，我连答题都没答，真恶心。新手机废了。
不过我用原来手机导出了皮肤。
[Alipay_CaifuMember.zip](https://github.com/user-attachments/files/16995134/Alipay_CaifuMember.zip)

**Comment by pidanpro** [comment]
> 噩耗，前两天看到小米社区说今年关闭BL解锁名额，我连答题都没答，真恶心。新手机废了。 不过我用原来手机导出了皮肤。 [Alipay_CaifuMember.zip](https://github.com/user-attachments/files/16995134/Alipay_CaifuMember.zip)

![Screenshot_2024-10-09-02-26-17-873_bin mt plus](https://github.com/user-attachments/assets/f8d7ddee-d20d-4526-b420-14a4bfddd4e5)
搜索出四个文件夹，不知道是哪个🤷‍♂️ 有视频教程吗？有点难度😭

**Comment by nov30th** [comment]
media 这个，没有视频，不过GPT出现以后还没更新过代码，我过段时间有空了让AI写个界面到app里面就方便了。

**Comment by pidanpro** [comment]
> 更新了app，做了界面，可以试试，有问题可以回复我或者新开一个issue

真不错，奈何我英语太差 界面跟反馈小窗都是英文的  看不懂 弄了截图翻译也没搞好 😭

**Comment by pidanpro** [comment]
> 更新了app，做了界面，可以试试，有问题可以回复我或者新开一个issue

![IMG_20241010_003216](https://github.com/user-attachments/assets/f7abf8a5-52b5-4079-b455-92cc4f258b86)
交作业，英文界面+英文反馈窗跟有些混乱的操作逻辑 折腾半小时终于弄好了✌️

**Comment by pidanpro** [comment]
> 更新了app，做了界面，可以试试，有问题可以回复我或者新开一个issue

![PIanA_dy1pl33pks4k7_原来支付宝还有黑色的我以为都是蓝色的#支付宝#黑色支付宝_1](https://github.com/user-attachments/assets/3c4561bb-6ce9-4535-bb33-f9dc59e10e61)
这个皮肤帅啊，可以搞吗？

**Comment by pidanpro** [comment]
> 更新了app，做了界面，可以试试，有问题可以回复我或者新开一个issue

![1](https://github.com/user-attachments/assets/6d2a1ce6-676b-4ead-8946-88aa147cfb46)
这个皮肤帅啊，可以搞吗？

**Comment by pidanpro** [comment]
> 更新了app，做了界面，可以试试，有问题可以回复我或者新开一个issue

![image](https://github.com/user-attachments/assets/503b9226-ae4a-40b6-8592-38761ec505f3)
这个皮肤帅啊，可以搞吗？

**Comment by nov30th** [comment]
不会涉及新的功能，只对原插件实现的付款界面功能的维护，并确保插件不会影响原app功能和性能。

**Comment by pidanpro** [comment]
![1](https://github.com/user-attachments/assets/846289ac-defc-4b0c-a56e-d6a8e81158a6)
为啥有人是这样的🤔

**Comment by nov30th** [comment]
没理解你要表达的是？

**Comment by pidanpro** [comment]
> 没理解你要表达的是？

付款码皮肤不一样 ，他这个皮肤跟模块自带的黑卡皮肤有啥区别

**Comment by nov30th** [comment]
我不知啊，都没看到对比，哪不一样了？

**Comment by pidanpro** [comment]
> 我不知啊，都没看到对比，哪不一样了？

![image](https://github.com/user-attachments/assets/968bae2d-30ce-4ab8-887e-3ecc12b95501)
![image](https://github.com/user-attachments/assets/c7d4de3b-0a27-48a0-b3d8-eaf550aa1c29)
贵人多忘事   图一是他人的  图二 模块的

**Comment by pidanpro** [comment]
> 我不知啊，都没看到对比，哪不一样了？

![image](https://github.com/user-attachments/assets/ba556c1f-8d5a-44e9-94e3-cdee712f2793)
![image](https://github.com/user-attachments/assets/63cf1831-1306-4fee-8342-e1bf1d19825d)

图一他人 图二模块

**Comment by nov30th** [comment]
条码先遮全，不然记得刷新。
图二是首次登录显示提示，和付款码没有关联。（作者不是支付宝员工，仅经验回答）
