### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by DrFx200522** [nov30th/AlipayHighHeadsomeRichAndroid#18]
后续版本能不能把支付码后面那一块白背景搞成模糊或透明呢，加个开关也可以，现在大概率挡脸挡主体

**Comment by nov30th** [comment]
emmmm, 目前的皮肤都是支付宝原始格式，实现的原理是替换了皮肤缓存，因此没有修改支付宝app逻辑。如果要透明的话理论上得hook资源调用，暂时不会去研究。
另外之前我很久之前用过小米手机锁屏或者展示可以直接调用支付宝二维码的，理论上你需要直接完全自定义展示的话，应该有类似的方法或者app实现一个完整的自定义界面。

**Comment by DrFx200522** [comment]
感谢回复，我去搜下

________________________________
发件人: ***@***.*** ***@***.***> 代表 nov30th ***@***.***>
发送时间: 2024年11月24日 0:29
收件人: nov30th/AlipayHighHeadsomeRichAndroid ***@***.***>
抄送: DrFx200522 ***@***.***>; Author ***@***.***>
主题: Re: [nov30th/AlipayHighHeadsomeRichAndroid] 小建议 (Issue #18)


emmmm, 目前的皮肤都是支付宝原始格式，实现的原理是替换了皮肤缓存，因此没有修改支付宝app逻辑。如果要透明的话理论上得hook资源调用，暂时不会去研究。
另外之前我很久之前用过小米手机锁屏或者展示可以直接调用支付宝二维码的，理论上你需要直接完全自定义展示的话，应该有类似的方法或者app实现一个完整的自定义界面。

―
