### ISSUE TITLE
会员等级修改失效

### ISSUE THREAD

**Issue by Juwan-Hwang** [nov30th/AlipayHighHeadsomeRichAndroid#19]
支付宝版本10.6.70.8100
会员等级修改失效
同时，若存在level_diamond文件夹，会显示默认皮肤

**Comment by wyfang** [comment]
+1

**Comment by nov30th** [comment]
这样啊…可小米9月完全关闭了root申请我的支付宝还在低版本为了自动收能量。
我有时间看下或者等等有没有小伙伴推pr

**Comment by wyfang** [comment]
> 这样啊…可小米9月完全关闭了bl申请我唯一解锁的支付宝还在低版本为了自动收能量。 我有时间看下或者等等有没有小伙伴推pr

收能量最新版都正常。芝麻粒最后版本或最新版芝麻糊，都正常工作。

**Comment by nov30th** [comment]
> > 这样啊…可小米9月完全关闭了bl申请我唯一解锁的支付宝还在低版本为了自动收能量。 我有时间看下或者等等有没有小伙伴推pr
> 
> 收能量最新版支付宝都正常。芝麻粒最后版本或最新版芝麻糊，都正常工作。

芝麻粒-TK? 好久没捣鼓了一直用constanline版，我试试。
更新最快可能也得这周末了, 中了个甲流emmm
