### ISSUE TITLE
作者还更新吗

### ISSUE THREAD

**Issue by wzgrx** [nov30th/AlipayHighHeadsomeRichAndroid#2]

**Comment by nov30th** [comment]
一直能用，就没有去更新。

**Comment by lqrqw** [comment]
2020年末打个卡，已经用不了了。付款界面是大众会员。豌豆荚下载的旧版支付宝10.0.12也不行了

**Comment by nov30th** [comment]
> 2020年末打个卡，已经用不了了。付款界面是大众会员。豌豆荚下载的旧版支付宝10.0.12也不行了

作者仍然可以用，你看看是不是有插件冲突之类。
