### ISSUE TITLE
2.4.0下载失败错误404

### ISSUE THREAD

**Issue by wyfang** [nov30th/AlipayHighHeadsomeRichAndroid#3]
其他版本可以下载。

**Comment by nov30th** [comment]
Github中release里下载失败可能是你使用的网络问题，尝试换一个网络。

**Comment by nov30th** [comment]
由于涉及资金类app，该项目执行文件只在当前repo的release中，不会在其他地方发布。[Xposed同步](https://repo.xposed.info/module/im.hoho.alipayinstallb)。
