### ISSUE TITLE
求一个和微X模块类似的功能

### ISSUE THREAD

**Issue by NiZerin** [nov30th/AlipayHighHeadsomeRichAndroid#7]
![WeChat Image_20220513111223](https://user-images.githubusercontent.com/18081398/168204079-f2af0096-ba8d-4ec1-ad2b-6411b3d078f9.jpg)
如图，这是微X模块的，伪造余额和余额宝

**Comment by nov30th** [comment]
建议fork源代码后自己修改，作者目前就自己只用皮肤功能。

**Comment by NiZerin** [comment]
好的，了解
