### ISSUE TITLE
还更新吗，新版本已失效

### ISSUE THREAD

**Issue by KaSock** [nov30th/AlipayHighHeadsomeRichAndroid#9]

**Comment by nov30th** [comment]
这样的吗？我自己都没用了官方皮肤太多了，我这两天瞅瞅

**Comment by nov30th** [comment]
10.5.20 对吗？可以正常使用啊。
是不是你新装的手机没有开存储权限？

**Comment by nov30th** [comment]
请描述失效功能，以及是否仅仅升级Alipay后功能失效。
目前作者手机上皮肤正常。
Issue先关闭，如果存在问题请重开。

**Comment by KaSock** [comment]
感谢响应，已经成功生效，是我忘记关issues了

**Comment by KaSock** [comment]
不知道什么原因，时而有效时而无效，权限点给了，支付宝版本是10.3.90.8000😂

**Comment by nov30th** [comment]
> 不知道什么原因，时而有效时而无效，权限点给了，支付宝版本是10.3.90.8000😂

清除一下xposed日志，然后无效的时候看看有没有error。每次展示日志会有记录的。有error的话贴上来我看看。

**Comment by KaSock** [comment]
> > 不知道什么原因，时而有效时而无效，权限点给了，支付宝版本是10.3.90.8000😂
> 
> 清除一下xposed日志，然后无效的时候看看有没有error。每次展示日志会有记录的。有error的话贴上来我看看。

![Screenshot_2023-09-18-11-23-23-704_com.android.shell.jpg](https://github.com/nov30th/AlipayHighHeadsomeRichAndroid/assets/56071624/94c66ac4-d6e5-4763-8580-cb2ac04087bd)

日志如图，模块没有生效，模块版本2.3.0

![IMG_20230918_112657.jpg](https://github.com/nov30th/AlipayHighHeadsomeRichAndroid/assets/56071624/6a9d6888-cf62-480a-b376-73f43c974640)

**Comment by KaSock** [comment]
现在已经不纠结钻石了，打开我的PS整整自定义玩玩😋

**Comment by KaSock** [comment]
> 现在已经不纠结钻石了，打开我的PS整整自定义玩玩😋

这也太戏剧了，我自定义出bug了钻石就好了😂
![IMG_20230918_232927.jpg](https://github.com/nov30th/AlipayHighHeadsomeRichAndroid/assets/56071624/ecdb7519-6188-4a76-8ddf-dd909af61eb6)
